#! /bin/bash

# Finding roots
# 4 line(s) hiddebn by BashToolDE! Marker: 26184 Your notes: Finding roots

# Variables
# 9 line(s) hiddebn by BashToolDE! Marker: 3286 Your notes: Variables

# Functions
# 8 line(s) hiddebn by BashToolDE! Marker: 4178 Your notes: Common function
# 55 line(s) hiddebn by BashToolDE! Marker: 8084 Your notes: Insertion functions
# 281 line(s) hiddebn by BashToolDE! Marker: 565 Your notes: Editing functions

# 32 line(s) hiddebn by BashToolDE! Marker: 22714 Your notes: Initialization
while [[ $Answer != "exit" ]]
do
  case $(echo $Answer | awk '{ print $1 }')
  in
# 182 line(s) hiddebn by BashToolDE! Marker: 19003 Your notes: Insertion commands
# 180 line(s) hiddebn by BashToolDE! Marker: 12726 Your notes: Editing commands
# 326 line(s) hiddebn by BashToolDE! Marker: 18996 Your notes: QL
# 13 line(s) hiddebn by BashToolDE! Marker: 17620 Your notes: Templates
# 72 line(s) hiddebn by BashToolDE! Marker: 6872 Your notes: Help
  esac
  read -p 'Type "help" to list options. Waiting for orders: ' Answer
  clear
done
echo "Bye! :)"
